version: '3'

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P1b7JBvP8II4
      MYSQL_DATABASE: sonarqube
      MYSQL_USER: sonarqube
      MYSQL_PASSWORD: P1b7JBvP8II4
    ports:
      - "3350:3306"

  sonarqube:
    depends_on:
      - db
    image: sonarqube:latest
    restart: always
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      SONARQUBE_JDBC_USERNAME: sonarqube
      SONARQUBE_JDBC_PASSWORD: P1b7JBvP8II4
      SONARQUBE_JDBC_URL: jdbc:mysql://127.0.0.1:3350/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
volumes:
  db_data: